name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '

        echo "Disk usage before cleanup:"
        df -h
        sudo rm -rf /var/log/* /tmp/*
        echo "Disk usage after cleanup:"
        df -h
        sudo rm -rf /usr/local/share/boost
        sudo apt-get clean
        df -h

        echo "Current directory: $(pwd)"
        echo "Listing home directory:"
        ls -la ~
        echo "Installing Node.js..."
        if ! command -v nvm &> /dev/null; then
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
        fi
        nvm install node
        echo "Installing PM2..."
        if ! command -v pm2 &> /dev/null; then
        npm install -g pm2
        fi
        REPO_URL="https://github.com/Bmccomiskey/S26-CPSC4910-Team05"
        BRANCH="main"
        REPO_DIR="$HOME/S26-CPSC4910-Team05"
        if [ -d "$REPO_DIR/.git" ]; then
          cd "$REPO_DIR"
          git pull origin "$BRANCH"
        else
          git clone "$REPO_URL" "$REPO_DIR"
          cd "$REPO_DIR"
        fi

        cd "$REPO_DIR"
        git fetch origin
        git merge origin/main

        cd "$REPO_DIR/gpid05/frontend"
        git fetch origin
        git merge origin/main
        
        npm start

        echo "Starting application"
        sudo systemctl restart team05-backend
        '
